### PR TITLE
Add CMake install targets.

### PR DESCRIPTION
**Pull request by moritz-h**
Follow up to https://github.com/LTLA/CppKmeans/pull/6.

This PR currently includes a find module for hnswlib, because upstream has no installed CMake config. I made an upstream PR for this (https://github.com/nmslib/hnswlib/pull/446). So maybe waiting here, if that gets merged, then the hnswlib find module can be removed here. Therefore, open as draft PR.

### CODE REVIEW

**Comment by LTLA** [comment]
I suppose we could add some CMake + preprocessor options to optionally eliminate the Annoy and/or HSNW dependencies, if it's too tedious to wait for them to work properly for you. In fact, I already have stuff like `KNNCOLLE_NO_ANNOY` macros, so if you have a CMake option, you could just set them.

**Comment by moritz-h** [comment]
This PR is already properly working in the current state, and could in theory be merged if the changes are ok for you. The hnswlib upstream changes would just solve it more cleanly and nicer, because `cmake/Findhnswlib.cmake` would not be required and the changes to `FetchContent_MakeAvailable(hnswlib)` could be reverted.

But having not much time the next 2.5 weeks anyway, just waiting a little more would be no problem from my side.

**Comment by moritz-h** [comment]
hnswlib accepted the PR to add CMake targets upstream. Therfore I could remove the find module and all required workarounds here. Only updated the hnswlib ref to latest upstream develop branch. So basically its the same as all previous PRs now and should be finished from my side.

**Comment by LTLA** [comment]
LGTM, mostly. Only one suggestion: replace the Annoy tag with the actual commit hash, which is a bit more tamper-proof (e.g., in the unlikely even that someone deletes the tag or silently changes it to point to a different hash.)

My other thought was that I would have liked for the **hnswlib** hash to point to a commit on their `master` rather than `develop` branch, but I guess that's no worse than a commit on my fork, so we'll just have to remember to update it when it gets merged in. That maintainer doesn't  seem to rebase or squash so we might not have to change anything, actually.

**Comment by moritz-h** [comment]
Did update to the Annoy commit hash.

hnswlib seems to use the master branch only for releases. Looking at the git history all development happens in `develop` and also PRs should target develop: https://github.com/nmslib/hnswlib#for-developers
They only merge develop into master when a new release tag is added.

**Comment by LTLA** [comment]
Done, thanks for the work.

**Pull request merged**
